version: "2.1"

services:
    app:
      build: .
      environment:
       DATABASE_NAME: GUC_Comments
      ports: 
        - 3000:8080
      depends_on: 
        db:
          condition: service_healthy
    db:
      image: healthcheck/postgres:alpine

      environment: 
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: root
        POSTGRES_DB: GUC_Comments