version: "2.1"

services:
    app:
      build: .
      environment:
        DATABASE_HOST: db
        DATABASE_USER: user
        DATABASE_PASSWORD: password
        DATABASE_NAME: name
        ACCESS_TOKEN: (a valid access token)
      ports: 
        - 3000:8080
      depends_on: 
        db:
          condition: service_healthy
    db:
      image: healthcheck/postgres:alpine

      environment: 
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: name